### ISSUE TITLE
application.css

### ISSUE THREAD

**Issue by vaskaloidis** [rstacruz/npm-pipeline-rails#17]
Hello,

I am using my application.scss file rather than my application.css file (I actually deleted my application.css file, because it is empty and it was conflicting with my Rails site (Rails started automatically using the application.css)) - 

But - when I try and use the Brunch generator, it fails here:

/Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/vasilioskaloidis/Code/Rails/tidbits/app/assets/stylesheets/application.css (Errno::ENOENT)

`
tidbits master % rails generate npm_pipeline:brunch
   identical  package.json
   identical  brunch-config.js
      append  app/assets/stylesheets/application.css
/Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/vasilioskaloidis/Code/Rails/tidbits/app/assets/stylesheets/application.css (Errno::ENOENT)
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:59:in `invoke!'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:180:in `append_to_file'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/npm-pipeline-rails-1.6.2/lib/generators/npm_pipeline/brunch_generator.rb:18:in `update_assets'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/generators.rb:180:in `invoke'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:145:in `generate_or_destroy'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:60:in `generate'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/vasilioskaloidis/Code/Rails/tidbits/vendor/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from bin/rails:4:in `<main>'

`

**Comment by sgnl** [comment]
I went ahead with the manual install to get it to work
